### PR TITLE
Update nvcomp's expected sizes when testing

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Comment by madsbk** [comment]
@thomcom is it possible to avoid hard coding the expected sizes? Can we get the sizes from somewhere? Or maybe use a range?

Anyways, I think we should merge this to get CI passing

**Comment by thomcom** [comment]
We could move them to a fixture in `conftest.py` but it doesn't improve the problem much. We're tracking very low level implementation details with these sizes: we could just drop them, but I think that the values are really nice-to-know.

I think most of these values have a single point of truth, so there's no extra API to validate them against. It wouldn't be unreasonable to move most or all to some kind of "extended tests" section that isn't run by CI?

**Comment by thomcom** [comment]
@gpucibot merge

**Comment by madsbk** [comment]
@gpucibot merge

**Comment by madsbk** [comment]
Thanks @thomcom

**Review by quasiben — APPROVED** [review]

**Comment by jakirkham** [comment]
Could we please raise this with the nvCOMP team? Maybe they can offer a better way of handling this so we don't need to hardcode things here

**Pull request merged**
