### PR TITLE
Add KvikIO devcontainers

### PR DESCRIPTION
**Pull request by trxcllnt**
## Description
This PR adds some [devcontainers](https://containers.dev/) to help simplify building the KvikIO C++ and Python libraries.

It also adds an optional job to the `pr.yaml` to [build the KvikIO libs in each devcontainer](https://github.com/trxcllnt/kvikio/blob/fea/devcontainers/.github/workflows/pr.yaml#L62-L68), so the build caches are populated for devs by CI.

A devcontainer can be launched by clicking the "Reopen in Container" button that VSCode shows when opening the repo (or by using the "Rebuild and Reopen in Container" command from the command palette):
image

Clicking this button will cause VSCode to prompt the user to select one of these devcontainer variants:
image

On startup, the devcontainer creates or updates the conda/pip environment using `kvikio/dependencies.yaml`. The envs/package caches are cached on the host via volume mounts, which are described in more detail in [`.devcontainer/README.md`](https://github.com/trxcllnt/kvikio/blob/fea/devcontainers/.devcontainer/README.md).

The container includes convenience functions to clean, configure, and build the various KvikIO components:

```shell
$ clean-kvikio-cpp # only cleans the C++ build dir
$ clean-kvikio-python # only cleans the Python build dir
$ clean-kvikio # cleans both C++ and Python build dirs

$ configure-kvikio-cpp # only configures kvikio C++ lib

$ build-kvikio-cpp # only builds kvikio C++ lib
$ build-kvikio-python # only builds kvikio Python lib
$ build-kvikio # builds both C++ and Python libs
```

* The C++ build script is a small wrapper around `cmake -S ~/kvikio/cpp -B ~/kvikio/cpp/build` and `cmake --build ~/kvikio/cpp/build`
* The Python build script is a small wrapper around `pip install --editable ~/kvikio/cpp`

Unlike `build.sh`, these convenience scripts *don't* install the libraries after building them. Instead, they automatically inject the correct arguments to build the C++ libraries from source and use their build dirs as package roots:

```shell
$ cmake -S ~/kvikio/cpp -B ~/kvikio/cpp/build
$ CMAKE_ARGS="-Dkvikio_ROOT=~/kvikio/cpp/build" \ # <-- this argument is automatic
  pip install -e ~/kvikio/cpp
```

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/kvikio/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by trxcllnt** [comment]
@madsbk looks like a temporary network issue:
```
121.2 W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Could you retry?

**Comment by madsbk** [comment]
> @madsbk looks like a temporary network issue:
> 
> ```
> 121.2 W: Some index files failed to download. They have been ignored, or old ones used instead.
> ```
> 
> Could you retry?

The same error :/
```
122.3 Reading package lists...
122.3 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'archive.ubuntu.com'
122.3 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
122.3 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
122.3 W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
122.3 W: Failed to fetch http://apt.llvm.org/jammy/dists/llvm-toolchain-jammy-16/InRelease  Temporary failure resolving 'apt.llvm.org'
122.3 W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/InRelease  Temporary failure resolving 'developer.download.nvidia.com'
122.3 W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'ppa.launchpad.net'
122.3 W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'packagecloud.io'
122.3 W: Some index files failed to download. They have been ignored, or old ones used instead.
122.3 Installing packages: bc jq sudo wget gettext-base bash-completion ca-certificates
```

I can access of the index files manually,

**Comment by trxcllnt** [comment]
Then maybe you have an issue with your docker bridge network. Can you build other containers that run `apt update`?

**Comment by madsbk** [comment]
> Then maybe you have an issue with your docker bridge network. Can you build other containers that run `apt update`?

Reinstalling docker fixed the issue, it works now thanks!

**Review by madsbk — APPROVED** [review]

**Review by AyodeAwe — APPROVED** [review]

**Pull request merged**
