### PR TITLE
Support of stream ordered device memory allocations (async mallocs)

### PR DESCRIPTION
**Pull request by madsbk**
Currently, we call `cuPointerGetAttribute(..., CU_POINTER_ATTRIBUTE_CONTEXT)` to set the CUDA context for each IO task. However, this doesn't work for[ stream ordered device memory allocations](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#pointer-attributes) so we now get the current cuda context instead.

Closes https://github.com/rapidsai/cudf/issues/12865

### CODE REVIEW

**Comment by quasiben** [comment]
I'm still seeing the same error with this PR as reported in https://github.com/rapidsai/cudf/issues/12865 .  Do you think I need to rebuild cuDF as well ?

**Comment by madsbk** [comment]
> I'm still seeing the same error with this PR as reported in [rapidsai/cudf#12865](https://github.com/rapidsai/cudf/issues/12865) . Do you think I need to rebuild cuDF as well ?

Yes, sorry should have made that clear. You have to build cudf with this PR, which can be done by setting the kvikio source cudf's `build.sh` script like:
```diff
diff --git a/build.sh b/build.sh
index bee66d819b..b6bcf5ce75 100755
--- a/build.sh
+++ b/build.sh
@@ -288,6 +288,7 @@ if buildAll || hasArg libcudf; then
           -DDISABLE_DEPRECATION_WARNINGS=${BUILD_DISABLE_DEPRECATION_WARNINGS} \
           -DCUDF_USE_PER_THREAD_DEFAULT_STREAM=${BUILD_PER_THREAD_DEFAULT_STREAM} \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
+          -DCPM_KvikIO_SOURCE=/home/mkristensen/repos/kvikio \
           ${EXTRA_CMAKE_ARGS}
 
     cd ${LIB_BUILD_DIR}
```

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
Thanks so much @madsbk !

**Pull request merged**
