### PR TITLE
nvcomp tests: update hardcoded lengths

### PR DESCRIPTION
**Pull request by madsbk**
@thomcom can we avoid hard coding the expected compression lengths?

### CODE REVIEW

**Comment by thomcom** [comment]
Seems like we could expect a range, or a maximum, or just not test them. 

1. Testing a range is like having hardcoded values with a lower frequency of changes required
2. Testing a maximum allows the results to improve in any way but makes us do leg work if the upstream team produces something with lower quality, potentially allowing us to flag it for them
3. Not testing the results leaves it in the hands of the NVCOMP team.

What do you suggest?

**Comment by madsbk** [comment]
Thanks @thomcom, we are now using `np.testing.assert_allclose(actual, desired, rtol=0.1)` when comparing sizes. I think that is sufficient for now.

**Comment by bdice** [comment]
Can this PR move forward? It is blocking #154 which in turn blocks GitHub Actions migrations. cc: @ajschmidt8

**Review by quasiben — APPROVED** [review]

**Pull request merged**
