### PR TITLE
Don't use CMake 3.25.0 as it has a FindCUDAToolkit show stopping bug

### PR DESCRIPTION
**Pull request by robertmaynard**
Also bring kvikio minimum required version inline with the rest of RAPIDS

### CODE REVIEW

**Review by vyasr — CHANGES_REQUESTED** [review]
This also needs to update the recipe meta.yaml files and the pyproject.toml file.

**Comment by robertmaynard** [comment]
> This also needs to update the recipe meta.yaml files and the pyproject.toml file.

Corrected.

**Review by galipremsagar — COMMENTED** [review]
Should we also update cmake minimum version in all Cmakelists.txt files? Similar to #147?

**Comment by robertmaynard** [comment]
> Should we also update cmake minimum version in all Cmakelists.txt files? Similar to #147?

Good point. Done.

**Review by galipremsagar — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
