### PR TITLE
Improve compatibility mode consistency

### PR DESCRIPTION
**Pull request by kingcrimsontianyu**
This PR adjusts the behavior of the file handle's compatibility mode to make it more consistent with its naming, i.e. `AUTO` actively falls back to the compatibility mode when any GDS step goes wrong; `OFF` sticks to the GDS path and errors out when things go wrong.

### CODE REVIEW

**Review by vuule — APPROVED** [review]

**Review by madsbk — COMMENTED** [review]
It would be good with a test. Is it possible to make a file path in testing that cannot be opened with the `O_DIRECT` flag?

**Comment by kingcrimsontianyu** [comment]
@madsbk Hmm. I'm not sure how to do that. OpenBSD does not support direct I/O, so open any file with this flag would fail, but I'm not sure how to cause the failure in a more generic, OS-agnostic way.
Imo,  mock test (https://github.com/rapidsai/kvikio/issues/556) is probably best suited for the compatibility mode-related test.

**Review by madsbk — APPROVED** [review]
Sounds good

**Comment by kingcrimsontianyu** [comment]
\merge

**Pull request merged**
