### PR TITLE
document channel_priority for conda

### PR DESCRIPTION
**Pull request by dcherian**
xref: https://github.com/rapidsai/kvikio/issues/94#issuecomment-1212164865

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
add to allowlist

**Comment by quasiben** [comment]
@rapidsai/ops can you merge when you have time ?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Comment by madsbk** [comment]
Thanks @dcherian !

**Pull request merged**
