### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by jakirkham**
Still WIP. Includes a couple changes to the recipes and CI scripts.

### CODE REVIEW

**Comment by jakirkham** [comment]
@charlesbluca do you recall what issues you were running into with the C++ build? Just want to make sure there are not other things I've missed here 🙂

**Comment by madsbk** [comment]
@jakirkham thanks for looking into this!

**Comment by charlesbluca** [comment]
@jakirkham my main issue was getting the follow up tests passing, which it seems like this PR does 🙂

**Comment by jakirkham** [comment]
Great thank you both! 😄

**Comment by jakirkham** [comment]
Cool sounds like this is all that is needed then. Marking as ready for review. Please let me know if you spot anything else 🙂

**Review by madsbk — APPROVED** [review]
LGTM, thanks @jakirkham !

**Comment by jakirkham** [comment]
Thanks Mads! 😄

**Pull request merged**
