### PR TITLE
Update to GCC 11

### PR DESCRIPTION
**Pull request by bdice**
This PR updates builds to use GCC 11.

### CODE REVIEW

**Comment by bdice** [comment]
This is ready for review, but please **_do not merge_** until all RAPIDS repos are ready to migrate. (I do not have privileges to add the DO NOT MERGE label to prohibit merging.)

**Review by madsbk — CHANGES_REQUESTED** [review]
Thanks @bdice, looks good.
We don't have a `DO NOT MERGE` label so I am setting `Request changes`.
Please let me know when this should be merged

**Review by jjacobelli — APPROVED** [review]

**Review by madsbk — APPROVED** [review]
LGTM, thanks

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
