### PR TITLE
Add stable channel install instruction

### PR DESCRIPTION
**Pull request by dcherian**
xref #94

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by madsbk** [comment]
add to allowlist

**Comment by madsbk** [comment]
@gpucibot add to allowlist

**Comment by madsbk** [comment]
@GPUtester add to allowlist

**Comment by madsbk** [comment]
ok to test

**Comment by madsbk** [comment]
@GPUtester ok to test

**Comment by madsbk** [comment]
rerun tests

**Comment by Ethyling** [comment]
ok to test

**Comment by madsbk** [comment]
Thanks @Ethyling :)

**Review by madsbk — APPROVED** [review]
Thanks @dcherian

**Pull request merged**
