### PR TITLE
Build and test with CUDA 12.5.1

### PR DESCRIPTION
**Pull request by KyleFromNVIDIA**
This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.

Contributes to https://github.com/rapidsai/build-planning/issues/73

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
There are a few more documentation places that should probably be updated.

https://github.com/rapidsai/kvikio/blob/363e2d65c02b216baf33e4219f27c0102936edee/cpp/doxygen/main_page.md#L40-L41

https://github.com/rapidsai/kvikio/blob/363e2d65c02b216baf33e4219f27c0102936edee/cpp/doxygen/main_page.md#L51-L52

https://github.com/rapidsai/kvikio/blob/363e2d65c02b216baf33e4219f27c0102936edee/docs/source/install.rst#L20-L21

https://github.com/rapidsai/kvikio/blob/363e2d65c02b216baf33e4219f27c0102936edee/docs/source/install.rst#L31-L32

xref: https://github.com/rapidsai/dask-cuda/pull/1357#pullrequestreview-2180844366

And this one that'll be broken by the changed conda env file name:

https://github.com/rapidsai/kvikio/blob/363e2d65c02b216baf33e4219f27c0102936edee/docs/source/install.rst#L48-L49

**Review by jameslamb — APPROVED** [review]
Thanks, looks good

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Kyle and James! 🙏

**Pull request merged**
