### PR TITLE
Use the `O_DIRECT` opened file in compatibility mode

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Comment by jakirkham** [comment]
Should this be moved to 22.08? Also appears there are conflicts

**Comment by madsbk** [comment]
> Should this be moved to 22.08? Also appears there are conflicts

Yes, this will have to be re-implemented. I saw some strange behaviors under testing of this PR so it got on hold. Will take a look when finding the time :)

**Comment by jakirkham** [comment]
No worries 😉

Thanks for the update Mads 🙏

**Comment by jakirkham** [comment]
Should we go ahead and move this to 22.10?

**Comment by madsbk** [comment]
> Should we go ahead and move this to 22.10?

Yes, targeting `branch-22.06` is a bit too late :)

**Comment by madsbk** [comment]
I am closing this PR, AFAICT the benefits does not outweigh the added complexity.

**Pull request closed without merging**
